# Generated by Django 4.1.3 on 2022-12-28 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('color', models.CharField(choices=[('blue', 'Azul'), ('orange', 'Laranja'), ('yellow', 'Amarelo'), ('red', 'Vermelho'), ('green', 'Verde'), ('pink', 'Rosa'), ('purple', 'Roxo')], default='azul', max_length=8)),
                ('contents', models.TextField(blank=True, max_length=1200, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('Sunday', 'Domingo'), ('Monday', 'Segunda-feira'), ('Tuesday', 'Terça-feira'), ('Wednesday', 'Quarta-feira'), ('Thursday', 'Quinta-feira'), ('Friday', 'Sexta-feira'), ('Saturday', 'Sábado')], max_length=9)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='studies.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Historic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('contents_studied', models.ManyToManyField(to='studies.content')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='studies.subject')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_list', to='studies.subject'),
        ),
    ]
