# Generated by Django 4.1.3 on 2022-12-28 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_alter_content_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_list', to='studies.subject'),
        ),
        migrations.AlterField(
            model_name='historic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studies.subject'),
        ),
    ]
