# Generated by Django 4.1.3 on 2022-12-29 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0005_alter_content_subject_alter_historic_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='studies.subject'),
        ),
    ]
