# Generated by Django 4.1.3 on 2022-11-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0005_subject_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(choices=[('azul', 'azel'), ('verde', 'verde'), ('vermelho', 'vermelho'), ('amarelo', 'amarelo')], default='azul', max_length=8),
        ),
    ]
