# Generated by Django 4.1.3 on 2023-01-17 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0006_alter_historic_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studies.subject'),
        ),
    ]
