# Generated by Django 4.1.3 on 2023-05-03 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0007_alter_historic_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studies.subject'),
        ),
    ]
