# Generated by Django 4.1.3 on 2022-11-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0007_alter_subject_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='initial_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='weekday',
            field=models.CharField(choices=[('Sunday', 'Domingo'), ('Monday', 'Segunda-feira'), ('Tuesday', 'Terça-feira'), ('Wednesday', 'Quarta-feira'), ('Thursday', 'Quinta-feira'), ('Friday', 'Sexta-feira'), ('Saturday', 'Sábado')], max_length=9),
        ),
    ]
