# Generated by Django 4.1.3 on 2022-11-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0008_study_initial_time_alter_study_weekday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='initial_time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='study',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
