# Generated by Django 4.1.3 on 2022-12-04 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studies', '0009_rename_initial_time_study_end_time_study_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subject',
            name='color',
            field=models.CharField(choices=[('azul', 'azul'), ('vermelho', 'vermelho'), ('verde', 'verde'), ('amarelo', 'amarelo')], default='azul', max_length=8),
        ),
    ]
