# Generated by Django 4.1.3 on 2022-12-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0014_alter_subject_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='subject',
            name='color',
            field=models.CharField(choices=[('blue', 'Azul'), ('orange', 'Laranja'), ('yellow', 'Amarelo'), ('red', 'Vermelho'), ('green', 'Verde'), ('pink', 'Rosa'), ('purple', 'Roxo')], default='azul', max_length=8),
        ),
    ]
