# Generated by Django 4.1.3 on 2022-12-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0016_alter_content_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(max_length=23),
        ),
    ]
