# Generated by Django 4.1.3 on 2022-12-08 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0018_alter_content_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_list', to='studies.subject'),
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
