# Generated by Django 4.1.3 on 2022-12-09 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0020_alter_content_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studies.subject'),
        ),
    ]
