# Generated by Django 4.1.3 on 2022-12-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0023_historic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='date',
            field=models.DateField(),
        ),
    ]
