# Generated by Django 4.1.3 on 2022-12-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0027_alter_content_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(max_length=2),
        ),
    ]
