# Generated by Django 4.1.3 on 2022-12-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0029_alter_content_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='contents',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=155),
        ),
    ]
