# Generated by Django 4.1.3 on 2022-12-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0030_alter_subject_contents_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='contents',
            field=models.TextField(blank=True, max_length=1200, null=True),
        ),
    ]
